from objectinspector import ObjectInspector
from objectpalette import ObjectPalette
from objecttree import ObjectTree
from restree import ResTree
from logwnd import LogWindow
from scriptwnd import ScriptWindow
from modelwnd import ModelWindow
from mainwnd import MainWindow
from mainmenu import MainMenu
from clipeditor import ClipEditor
from scratchboard import ScratchBoard
